version: '3.3'

services:
  node-dev-server:
    build:
      dockerfile: Dockerfile
      context: ./server
    restart: unless-stopped
    volumes:
      - ./server/:/app
      - server_node_modules:/app/node_modules/
    ports:
      - "3001:3001"
    env_file:
      - server/.env
    command: npm run dev
  react-client:
    build:
      dockerfile: Dockerfile
      context: ./client
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - client/.env
volumes:
  server_node_modules: {}

